[package]
name = "papagaia-overlay"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false }
serde_json.workspace = true
papagaia-core = { path = "../papagaia-core" }
glib = "0.22.7"
gtk4 = "0.11.3"
gtk4-layer-shell = "0.8.0"
